// src/themes.js
export const themes = {
    dark: {
      primary: '#202020',
      secondary: '#3ee3f3',
      secondary2: '#3ee3f3',
      tertiary: '#202020',
      background: '#202020',
      background2: '#FFFFFF',
      backgroundContainer: '#202020',
      backgroundTextInput: '#202020',
      backgroundPainel: '#202020',
      text: '#FFFFFF',
      text2: '#202020',
      text3: '#202020',
      text3: '#202020',
      text4: '#FFFFFF',
      textHolder: '#202020',
      textTitulos: '#FFFFFF',
      textTitulos2: '#FFFFFF',
      button: '#bab8b5',
      button2: '#bab8b5',
      button3: '#3ee3f3',
      buttonTextInput: '#C0C0C0',
      textButton: '#000000',
      botaoplustarefa: '#C0C0C0',
      border: '#FFFFFF',
      borderbutton: '#FFFFFF',
      bordercontainerborda: '#C0C0C0',
      bordercontainerborda2: '#FFFFFF',
      placeholder: '#FFFFFF',
      alerts: '#3ee3f3',
      sinaldeMais: '#FFFFFF',
      textNivel: 'white',
      progressNivelCor: '#FFFFFF',
      logo: require('../../assets/XPLogoPreto.png'), // Imagem para o tema escuro
      Icone0: require('../../assets/XPIcone0Preto.png'), // Imagem para o tema claro
      sound: require('../../assets/DarkSound.mp3'), // Imagem para o tema claro
      botaoAprimoramento: require('../../assets/BotaoAprimoramentoAzul.png'),
      botaoEstudos: require('../../assets/BotaoEstudosPreto.png'),
      botaoTarefas: require('../../assets/BotaoTarefasPreto.png'),
      botaoMemorias: require('../../assets/BotaoMemoriasAzul.png'),
      botaoSelecionarTema: require('../../assets/botaoSelecionarTemaBranco.png'),
      botaoRelogar: require('../../assets/botaoRelogarBranco.png'),
      bordaGame: 'blue',
      bordabordaGameBackground: '#FFFFFF',
      bordabordaGameBackground2:'#C0C0C0',
      bordaCardGame: '#FFFFFF',
      textoTituloBordaCardGame:'white',
      botaoReiniciarCor:'#202020',
      gameLevel2Text:'black',
      bordaContainerComponente: 'black',
      bordaContainerComponente2: 'black',
      dataMensagemMemoriaTextoCor: '#3ee3f3',
      botaoEnviarMemoriaCor: 'white',
      limiteAtingidoCor: 'white',
      fundoBotaoJogoSombra: 'white',
      bordaContainerPowerMemoria: '#202020',
      bordaContainerComponentePainel: "white",
      textoShadowComponentes: 'black',
      textoLinkLogin: '#3ee3f3',


    },
    light: {
      primary: '#FFFFFF',
      secondary: '#202020',
      secondary2: '#202020',
      tertiary: '#202020',
      background: '#FFFFFF',
      background2: '#202020',
      backgroundContainer: '#C0C0C0',
      backgroundTextInput: '#202020',
      backgroundPainel: '#202020',
      text: '#202020',
      text2: '#202020',
      text3: '#202020',
      text4: '#202020',
      textHolder: '#202020',
      textTitulos: '#FFFFFF',
      textTitulos2: '#FFFFFF',
      button: '#C0C0C0',
      button2: '#C0C0C0',
      button3: '#C0C0C0',
      buttonTextInput: '#C0C0C0',
      textButton: '#000000',
      botaoplustarefa: '#C0C0C0',
      border: '#FFFFFF',
      borderbutton: '#202020',
      bordercontainerborda: '#C0C0C0',
      bordercontainerborda2: '#FFFFFF',
      placeholder: '#FFFFFF',
      alerts: '#3ee3f3',
      sinaldeMais: '#202020',
      textNivel: 'white',
      progressNivelCor: '#3ee3f3',
      logo: require('../../assets/XPLogoBranco.png'), // Imagem para o tema claro
      Icone0: require('../../assets/XPIcone0Branco.png'), // Imagem para o tema claro
      sound: require('../../assets/WhiteSound.mp3'), // Imagem para o tema claro
      botaoAprimoramento: require('../../assets/BotaoAprimoramentoPreto.png'),
      botaoEstudos: require('../../assets/BotaoEstudosPreto.png'),
      botaoTarefas: require('../../assets/BotaoTarefasPreto.png'),
      botaoMemorias: require('../../assets/BotaoMemoriasPreto.png'),
      botaoSelecionarTema: require('../../assets/botaoSelecionarTema.png'),
      botaoRelogar: require('../../assets/botaoRelogarPreto.png'),
      bordaGame: 'blue',
      bordabordaGameBackground:'#202020',
      bordabordaGameBackground2:'#FFFFFF',
      bordaCardGame: '#FFFFFF',
      textoTituloBordaCardGame:'white',
      botaoReiniciarCor:'#202020',
      gameLevel2Text:'#3ee3f3',
      bordaContainerComponente: '#FFFFFF',
      bordaContainerComponente2: '#3ee3f3',
      dataMensagemMemoriaTextoCor: '#FFFFFF',
      botaoEnviarMemoriaCor: 'white',
      limiteAtingidoCor: 'white',
      fundoBotaoJogoSombra: 'white',
      bordaContainerPowerMemoria: '#202020',
      bordaContainerComponentePainel: "#3ee3f3",
      textoShadowComponentes: '#3ee3f3',
      textoLinkLogin: '#3ee3f3',




    },
    blue: {
      primary: '#3ee3f3',
      secondary: '#FFFFFF',
      secondary2: '#FFFFFF',
      tertiary: '#202020',
      background: '#3ee3f3',
      background2: '#202020',
      backgroundContainer: '#3ee3f3',
      backgroundTextInput: '#202020',
      backgroundPainel: '#202020',
      text: '#FFFFFF',
      text2: '#202020',
      text3: '#202020',
      text4: '#FFFFFF',
      textHolder: '#202020',
      textTitulos: '#FFFFFF',
      textTitulos2: '#FFFFFF',
      button: '#FFFFFF',
      button2: '#FFFFFF',
      button3: '#C0C0C0',
      buttonTextInput: '#C0C0C0',
      textButton: '#000000',
      botaoplustarefa: '#000000',
      border: '#FFFFFF',
      borderbutton: '#FFFFFF',
      placeholder: '#C0C0C0',
      bordercontainerborda: '#C0C0C0',
      bordercontainerborda2: '#FFFFFF',
      alerts: '#C0C0C0',
      textNivel: 'white',
      progressNivelCor: '#3ee3f3',
      logo: require('../../assets/XPLogoAzul.png'), // Imagem para o tema azul
      Icone0: require('../../assets/XPIcone0Azul.png'), // Imagem para o tema claro
      sound: require('../../assets/CelestialSound.mp3'), // Imagem para o tema claro
      botaoAprimoramento: require('../../assets/BotaoAprimoramentoAzul.png'),
      botaoEstudos: require('../../assets/BotaoEstudosAzul.png'),
      botaoTarefas: require('../../assets/BotaoTarefasAzul.png'),
      botaoMemorias: require('../../assets/BotaoMemoriasAzul.png'),
      botaoSelecionarTema: require('../../assets/botaoSelecionarTema.png'),
      botaoRelogar: require('../../assets/botaoRelogarPreto.png'),
      bordaGame: 'blue',
      bordabordaGameBackground:'white',
      bordabordaGameBackground2:'#3ee3f3',
      bordaCardGame: '#FFFFFF',
      textoTituloBordaCardGame:'white',
      botaoReiniciarCor:'#202020',
      gameLevel2Text:'black',
      bordaContainerComponente: '#FFFFFF',
      bordaContainerComponente2: '#FFFFFF',
      dataMensagemMemoriaTextoCor: '#202020',
      botaoEnviarMemoriaCor: 'white',
      limiteAtingidoCor: 'white',
      fundoBotaoJogoSombra: '#3ee3f3',
      bordaContainerPowerMemoria: '#202020',
      bordaContainerComponentePainel: "white",
      textoShadowComponentes: 'black',
      textoLinkLogin: '#202020',




    },
    pink: {
      primary: '#FF3EB5',
      secondary: '#FF3EB5',
      secondary2: '#FF3EB5',
      tertiary: '#202020',
      background: '#C0C0C0',
      background2: '#FFFFFF',
      backgroundContainer: '#C0C0C0',
      backgroundTextInput: '#202020',
      backgroundPainel: '#202020',
      text: '#FFFFFF',
      text2: '#FF3EB5',
      text3: '#202020',
      text4: '#202020',
      textTitulos: '#FFFFFF',
      textTitulos2: '#FFFFFF',
      textHolder: '#FF3EB5',
      button: '#FFFFFF',
      button2: '#FF3EB5',
      button3: '#FF3EB5',
      buttonTextInput: '#C0C0C0',
      textButton: '#000000',
      botaoplustarefa: '#C0C0C0',
      border: '#FF3EB5',
      borderbutton: '#FFFFFF',
      bordercontainerborda: '#C0C0C0',
      bordercontainerborda2: '#FF3EB5',
      placeholder: '#FF3EB5',
      alerts: '#FFFFFF',
      textNivel: 'white',
      progressNivelCor: '#FF3EB5',
      logo: require('../../assets/XPLogoKawai.png'), // Imagem para o tema azul
      Icone0: require('../../assets/XPIcone0Kawai.png'), // Imagem para o tema claro
      sound: require('../../assets/PinkSound.mp3'), // Imagem para o tema claro
      botaoAprimoramento: require('../../assets/BotaoAprimoramentoRosa.png'),
      botaoEstudos: require('../../assets/BotaoEstudosRosa.png'),
      botaoTarefas: require('../../assets/BotaoTarefasRosa.png'),
      botaoMemorias: require('../../assets/BotaoMemoriasRosa.png'),
      botaoSelecionarTema: require('../../assets/botaoSelecionarTemaRosa.png'),
      botaoRelogar: require('../../assets/botaoRelogarRosa.png'),
      bordaGame: '#FF3EB5',
      bordabordaGameBackground:'white',
      bordabordaGameBackground2:'#C0C0C0',
      bordaCardGame: '#FFFFFF',
      textoTituloBordaCardGame:'white',
      botaoReiniciarCor:'#FF3EB5',
      gameLevel2Text:'black',
      bordaContainerComponente: '#FF3EB5',
      bordaContainerComponente2: '#FF3EB5',
      dataMensagemMemoriaTextoCor: '#FF3EB5',
      botaoEnviarMemoriaCor: 'white',
      limiteAtingidoCor: '#FF3EB5',
      fundoBotaoJogoSombra: '#FF3EB5',
      bordaContainerPowerMemoria: '#202020',
      bordaContainerComponentePainel: "#FF3EB5",
      textoShadowComponentes: '#FF3EB5',
      textoLinkLogin: '#FF3EB5',



    },
    unicorn: {
      primary: '#FF3EB5',
      secondary: '#202020',
      secondary2: '#202020',
      tertiary: '#202020',
      background: '#ffffff',
      background2: '#3ee3f3',
      backgroundContainer: '#C0C0C0',
      backgroundTextInput: '#202020',
      backgroundPainel: '#202020',
      text: '#FF3EB5',
      text2: '#ffffff',
      text3: '#ffffff',
      textHolder: '#202020',
      textTitulos: '#FFFFFF',
      textTitulos2: '#FFFFFF',
      button: '#C0C0C0',
      button2: '#FF3EB5',
      button3: '#FF3EB5',
      buttonTextInput: '#C0C0C0',
      textButton: '#000000',
      botaoplustarefa: '#C0C0C0',
      border: '#3ee3f3',
      borderbutton: '#FF3EB5',
      bordercontainerborda: '#C0C0C0',
      bordercontainerborda2: '#FFFFFF',
      placeholder: '#FF3EB5',
      alerts: '#3ee3f3',
      textNivel: 'white',
      progressNivelCor: '#FF3EB5',
      logo: require('../../assets/XPLogoUnicornio.png'), // Imagem para o tema azul
      Icone0: require('../../assets/XPIcone0Unicornio.png'), // Imagem para o tema claro
      sound: require('../../assets/UnicornioSound.mp3'), // Imagem para o tema claro
      botaoAprimoramento: require('../../assets/BotaoAprimoramentoRosa.png'),
      botaoEstudos: require('../../assets/BotaoEstudosRosa.png'),
      botaoTarefas: require('../../assets/BotaoTarefasAzul.png'),
      botaoMemorias: require('../../assets/BotaoMemoriasRosa.png'),
      botaoSelecionarTema: require('../../assets/botaoSelecionarTemaRosa.png'),
      botaoRelogar: require('../../assets/botaoRelogarAzul.png'),
      bordaGame: 'blue',
      bordabordaGameBackground:'#3ee3f3',
      bordabordaGameBackground2:'#FFFFFF',
      bordaCardGame: '#FFFFFF',
      textoTituloBordaCardGame:'#3ee3f3',
      botaoReiniciarCor:'#202020',
      gameLevel2Text:'black',
      bordaContainerComponente: '#FF3EB5',
      bordaContainerComponente2: '#3ee3f3',
      dataMensagemMemoriaTextoCor: '#FF3EB5',
      botaoEnviarMemoriaCor: '#FF3EB5',
      limiteAtingidoCor: 'white',
      fundoBotaoJogoSombra: '#3ee3f3',
      bordaContainerPowerMemoria: '#202020',
      bordaContainerComponentePainel: "#3ee3f3",
      textoShadowComponentes: '#3ee3f3',
      textoLinkLogin: '#3ee3f3',



    },
  };
  